### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "t.berthod@outlook.com",
  "username": "Theo",
  "password": "bonjouratous"
}

### Log
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "t.berthod@outlook.com",
  "password": "bonjouratous"
}

### Add a sneaker to the collection of the user with the id 1
POST http://localhost:3000/api/collection
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MDIzODAxMjksImV4cCI6MTcwMjM4MzcyOX0.VtR_dy-9PZaDaLcFwHlfp52SjyB-AkewE9LPK5IP4Eg

{
  "sneaker_id": 3109
}

### Pass the sneaker in the wishList
POST http://localhost:3000/api/wishlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MDIzODAxMjksImV4cCI6MTcwMjM4MzcyOX0.VtR_dy-9PZaDaLcFwHlfp52SjyB-AkewE9LPK5IP4Eg

{
  "sneaker_id": 3109
}

### GET a collection
GET http://localhost:3000/api/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MDIzNzk1MDQsImV4cCI6MTcwMjM4MzEwNH0.Eq2X41lWbH343Qw4R3Tr-B8uiUxXMkSarRtpG5hVtHQ

### DELETE a sneaker of collection
DELETE http://localhost:3000/api/collection/3109
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MDIxNDc5NDksImV4cCI6MTcwMjE1MTU0OX0.Mr-SHsPw8JCWiv6Rw1IT6BtE4dp3l-H2nwUqZ7xOYAQ